name: 'test'
on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Build
        uses: buildtool/build-action@v1
        with:
          dockerfile: Dockerfile
